EXECUTABLES = ch1a ch1b ch1c 

all: $(EXECUTABLES)

clean:
	rm -f core *.o $(EXECUTABLES) a.out


ch1a: ch1a.c
	$(CC) $(CFLAGS) -o ch1a ch1a.c

ch1b: ch1b.c
	$(CC) $(CFLAGS) -o ch1b ch1b.c

ch1c: ch1c.c
	$(CC) $(CFLAGS) -o ch1c ch1c.c
